name: "Frogbot Scan Repository"

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    # Runs automatically once a day at midnight GMT
    - cron: "0 0 * * *"
  push:
    branches:
      - main # Change to 'master' if that is your default branch

permissions:
  pull-requests: write
  contents: write
  security-events: write
  id-token: write # MANDATORY for OIDC authentication

env:
  JF_URL: ${{ vars.JF_URL }}
  # Uses GitHub's built-in token to allow Frogbot to open PRs and comment
  JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  scan-repository:
    runs-on: ubuntu-latest
    name: Scan Repository
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0 is CRUCIAL for Frogbot to get full Git history and prevent shallow clone errors
          fetch-depth: 0

      - name: Run Frogbot
        uses: jfrog/frogbot@v3
        with:
          # Must match the Provider Name created in Step 1
          oidc-provider-name: "amitesh-frogbot-jfrog"
